#!/usr/bin/env python3

import subprocess
import sys

def bce(expr):
 bc = subprocess.Popen(["bc", "-q"], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
 bc.stdin.write((expr + "\n" if not expr.endswith("\n") else expr).encode("utf-8"))
 bc.stdin.flush()
 bc.stdin.close()
 c = bc.wait()
 r = bc.stdout.read().decode("utf-8").strip()
 return r, c

def main(argv):
 r, c = bce(" ".join(argv[1:]))
 print(r)
 return c

if __name__ == "__main__":
 try:
  sys.exit(main(sys.argv))
 except KeyboardInterrupt:
  pass
