#!/usr/bin/env python2

import subprocess
import sys

bc = subprocess.Popen(["bc", "-q", "-l"], stdin=subprocess.PIPE)
bc.stdin.write(" ".join(sys.argv[1:]) + "\n")
bc.stdin.flush()
bc.stdin.close()
bc.wait()
