#!/usr/bin/env python

import sys
import time

from datetime import date, timedelta
from time import gmtime, localtime, strptime as _strptime

def dbd(date1, date2="today", fmt="%Y-%m-%d"):
 today = localtime()[:3]
 special = dict(
  today=date(*today),
  yesterday=date(*today) - timedelta(days=1),
  tomorrow=date(*today) + timedelta(days=1),
 )
 date1 = special[date1] if date1 in special else date(*strptime(date1, fmt)[:3])
 date2 = special[date2] if date2 in special else date(*strptime(date2, fmt)[:3])
 return (date2 - date1).days

def strptime(s, fmt):
 if fmt == "%s":
  return gmtime(int(s))
 return _strptime(s, fmt)
  
if __name__ == "__main__":
 usage = "Usage: %s [+format (strftime)] date1|word [date2|word]\n" % sys.argv[0]
 usage += "word is one of today, yesterday, or tomorrow"
 
 if len(sys.argv) < 2 or len(sys.argv) > 4:
  print usage
  sys.exit(2)
 
 if sys.argv[1] in ("-h", "--help"):
  print usage
  sys.exit()
 elif sys.argv[1].startswith("+"):
  if len(sys.argv) < 3:
   print usage
   sys.exit(2)
  fmt = sys.argv[1][1:]
  date1 = sys.argv[2]
  date2 = sys.argv[3] if len(sys.argv) > 3 else "today"
 else:
  fmt = "%Y-%m-%d"
  date1 = sys.argv[1]
  date2 = sys.argv[2] if len(sys.argv) > 2 else "today"
 
 try:
  print dbd(date1, date2, fmt)
 except ValueError as exc:
  print "error:", exc
  sys.exit(2)
