#!/usr/bin/env python2

import sys
import time

from datetime import date, timedelta
from time import gmtime, localtime, strptime as _strptime

def dbd(date1, date2="today", fmt="%Y-%m-%d"):
 today = localtime()[:3]
 special = dict(
  today=date(*today),
  yesterday=date(*today) - timedelta(days=1),
  tomorrow=date(*today) + timedelta(days=1),
 )
 date1 = special[date1] if date1 in special else date(*strptime(date1, fmt)[:3])
 date2 = special[date2] if date2 in special else date(*strptime(date2, fmt)[:3])
 return (date2 - date1).days

def strptime(s, fmt):
 if fmt == "%s":
  return gmtime(int(s))
 return _strptime(s, fmt)
  
def main(argv):
 usage = "Usage: %s [+format (strftime)] date1|word [date2|word]\n" % argv[0]
 usage += "word is one of today, yesterday, or tomorrow"
 
 if len(argv) < 2 or len(argv) > 4:
  print >> sys.stderr, usage
  return 2
 
 if argv[1] in ("-h", "--help"):
  print usage
  return 0
 elif argv[1].startswith("+"):
  if len(argv) < 3:
   print >> sys.stderr, usage
   return 2
  fmt = argv[1][1:]
  date1 = argv[2]
  date2 = argv[3] if len(argv) > 3 else "today"
 else:
  fmt = "%Y-%m-%d"
  date1 = argv[1]
  date2 = argv[2] if len(argv) > 2 else "today"
 
 try:
  print dbd(date1, date2, fmt)
 except ValueError as exc:
  print >> sys.stderr, "error:", exc
  return 2

if __name__ == "__main__":
 try:
  sys.exit(main(sys.argv))
 except KeyboardInterrupt:
  pass
