#!/usr/bin/env python3

import argparse
import html.entities
import re
import sys

from typing import *


def char2entity(char: str) -> str:
 return "&%s;" % html.entities.codepoint2name.get(ord(char), "#x%s" % hex(ord(char))[2:])


def entity2char(entity: str) -> Optional[str]:
 entity = re.match(r"^&?(.*?);?$", entity).group(1)
 if re.match(r"^#([0-9]+)$", entity):
  return chr(int(entity[1:], 10))
 if re.match(r"^#x([0-9a-fA-F]+)$", entity):
  return chr(int(entity[2:], 16))
 codepoint = html.entities.name2codepoint.get(entity, None)
 return chr(codepoint) if codepoint else None


def main(argv: List[str]) -> int:
 p = argparse.ArgumentParser()
 p.add_argument("-x", "--code-point", "--hex", dest="code_point", action="store_true",
                help="show the version number and exit")
 p.add_argument("input", metavar="entity-or-char",
                help="the character to convert to an entity or"
                     " the entity to convert to a character")
 try:
  args = p.parse_args(argv[1:])
 except SystemExit as exc:
  return exc.code
 
 input_ = args.input
 mode   = (char2entity if len(input_) == 1 else entity2char)
 result = mode(input_)
 if result is None:
  print("error: invalid entity %s" % repr(input_), file=sys.stderr)
  return 1
 
 if args.code_point:
  if mode == char2entity:
   result = input_
  sys.stdout.write("U+" + re.sub(r"^0x", "", hex(ord(result))))
 else:
  sys.stdout.write(result)
 
 if sys.stdout.isatty():
  print()
 
 return 0


if __name__ == "__main__":
 try:
  sys.exit(main(sys.argv))
 except KeyboardInterrupt:
  pass
