#!/bin/bash

# My (Scott Zeid) script to start Firefox

# Distribution version
FIREFOX_CMD=/usr/bin/firefox

# Custom install
if [ -x ~/opt/holly/holly ]; then
 FIREFOX_CMD=~/opt/holly/holly
fi

exec $FIREFOX_CMD $@
