#!/bin/sh

# My (Scott Zeid) script to start Firefox


# Distribution version
distribution=/usr/bin/firefox

# Custom install
custom=~/opt/firefox


if [ -d "$custom" ] && [ -x "$custom/run" ]; then
 cmd="rundir $custom"
elif [ -x "$custom" ]; then
 cmd=$custom
else
 cmd=$distribution
fi

exec $cmd $@
