#!/bin/bash

# My (Scott Zeid) script to start Firefox

# Distribution version
FIREFOX_CMD=/usr/bin/firefox

# Custom install
if [ -x ~/opt/firefox-beta/firefox ]; then
 FIREFOX_CMD=~/opt/firefox-beta/firefox
fi

exec $FIREFOX_CMD $@
