#!/bin/bash

DEFAULT_USER=root

if [ -z "$1" -o -z "$2" ]; then
 echo "Usage: $0 apk [username@]device-address [pm options [...]]" >&2
 echo "(username defaults to $DEFAULT_USER)" >&2
 exit 2
fi

APK="$1"
DEVICE="$2"
shift 2

if grep -v -q -e '@' <<< "$DEVICE"; then
 DEVICE="$DEFAULT_USER@$DEVICE"
fi

TMP_NAME=/sdcard/.install-apk.tmp.apk

echo ssh "$DEVICE" pm install -r "$@" "$TMP_NAME"
scp -p "$APK" "$DEVICE":"$TMP_NAME"
[ $? -eq 0 ] && ssh "$DEVICE" pm install -r "$@" "$TMP_NAME"
[ $? -eq 0 ] && ssh "$DEVICE" rm -f "$TMP_NAME"
