#!/bin/bash

# Compile and run a Java source file.  (javat stands for "Java Test".)
# Requires a program called `javawrapper` in your $PATH that takes a .class
# file and executes the class contained within it.  Such a program can be
# found at <http://code.s.zeid.me/bin/src/master/javawrapper>.

if [ -z "$1" ]; then
 echo "Usage: $0 file.java" >&2
 exit 1
fi

SRC=`printf '%s' "$1" | sed 's/\.class$/.java/g'`
CLS=`printf '%s' "$SRC" | sed 's/\.java$/.class/g'`

shift

javac "$SRC"
R=$?
[ $R -eq 0 ] && javawrapper "$CLS" "$@" || exit $R
