#!/bin/sh
set -e

main() {
 local path
 for arg; do
  if printf '%s\n' "$arg" | head -n 1 | grep -q -e '^[^-]'; then
   path=$arg
   break
  fi
 done
 
 if [ x"$path" = x"" ]; then
  echo "Usage: $(basename -- "$0") [ls options] {path}" >&2
  return 2
 fi
 
 if [ -d "$path" ]; then
  local ls_args; ls_args=$LS_ARGS
  if [ -t 1 ]; then
   if [ x"$ls_args" = x"" ]; then
    if ls --color=auto /dev/null >/dev/null 2>&1; then
     ls_args="$ls_args --color=auto"
    fi
   fi
  fi
  ls $ls_args "$@"
 else
  cat "$path"
 fi
}


main "$@"
