#!/bin/sh

SCRIPT=$0

usage() {
 echo "Usage: $SCRIPT <file> [attr] [command] [args [...]]"
 echo "       $SCRIPT --help"
 echo
 echo "Commands:"
 echo "  ls                    Lists attributes (the default if no command is"
 echo "                        given)."
 echo "  get                   Gets the attribute's value."
 echo "  set/= [value]         Sets the attribute to the given value, or the"
 echo "                        contents of standard input if no value is given."
 echo "  rm                    Removes the attribute."
}

main() {
 if [ x"$1" = x"--" ]; then
  shift
 elif [ x"$1" = x"-h" ] || [ x"$1" = x"--help" ]; then
  usage
  return 0
 elif [ $# -lt 1 ]; then
  usage >&2
  return 2
 fi
 
 local file=$1
 shift
 if [ $# -ge 1 ]; then
  local attr=$1
  shift
 else
  local attr=
 fi
 if [ $# -ge 1 ]; then
  local cmd=$1
  shift
 else
  local cmd=
 fi
 if [ x"$attr" = x"" ]; then
  cmd=ls
 elif [ x"$cmd" = x"" ]; then
  cmd=get
 elif [ x"$cmd" = x"=" ]; then
  cmd=set
 fi
 case "$cmd" in
  ls)
   attr_"$cmd" "$file" "$@"
   ;;
  get|set|rm)
   attr_"$cmd" "$file" "$attr" "$@"
   return $?
   ;;
  *)
   usage >&2
   return 2
 esac
}
 
attr_ls() {
 local file=$1
 if [ x"`uname -s`" = x"Linux" ] && (which semanage >/dev/null 2>&1); then
  attr -q -l "$1" | grep -v '^selinux$'
 else
  attr -q -l "$1"
 fi
}

attr_get() {
 local file=$1
 local attr=$2
 attr -q -g "$attr" "$file"
 if [ $? -eq 0 ] && [ -t 1 ]; then
  echo
 fi
}

attr_set() {
 local file=$1
 local attr=$2
 shift 2
 if [ $# -ne 0 ]; then
  local value=$@
  attr -q -s "$attr" -V "$value" "$file"
 else
  attr -q -s "$attr" "$file"
 fi
}

attr_rm() {
 local file=$1
 local attr=$2
 attr -q -r "$attr" "$file"
}

main "$@"
