#!/usr/bin/env python3

import re
import sys


COLORS = {
 0:0, 1:4, 2:2, 3:6, 4:1, 5:5, 6:3, 7:7, 8:0, 9:4,
}
COLORS.update(dict(
 A=2, B=6, C=1, D=5, E=3, F=7, a=2, b=6, c=1, d=5, e=3, f=7,
))


def colors_to_ansi(text):
 text = text.split("\n")
 for i in range(len(text)):
  line = text[i]
  for j in COLORS:
   intense = (1 if isinstance(j, str) or j > 7 else 0)
   line = re.sub("((\xa7|&)%s)" % j,
                 '\x1b[%dm\x1b[3%dm' % (intense, COLORS[j]),
                 line)
  line = ("\x1b[0m%s\x1b[0m" % line)
  text[i] = line
 return "\n".join(text)


def main(argv):
 text = " ".join(argv[1:])
 if not text:
  text = sys.stdin.read()
  if sys.stdin.isatty():
   print(file=sys.stderr)
 print(colors_to_ansi(text))


if __name__ == "__main__":
 sys.exit(main(sys.argv)) 
