#!/bin/bash

LAUNCHERS=~/.minecraft/launchers

JAVA_HOME="`readlink -f \`which java\` | sed -e "s:/bin/java::"`"
if [ "`uname -i`" = "x86_64" ]; then
 export LD_LIBRARY_PATH="$JAVA_HOME/lib/amd64"
else
 export LD_LIBRARY_PATH="$JAVA_HOME/lib/i386"
fi
if [ "$1" = "--stock-launcher" ]; then
 shift
 java -jar "$LAUNCHERS"/Minecraft.jar "$@"
elif [ "$1" = "--dev" ]; then
 shift
 java -jar "$LAUNCHERS"/MinecraftDev.jar "$@"
else
 java -jar "$LAUNCHERS"/MagicLauncher.jar "$@"
fi
