#!/usr/bin/env python3

import os
import sys
import urllib.parse

import gi  # apt install python3-gi

gi.require_version("Gtk", "3.0")  # apt install gir1.2-gtk-3.0
from gi.repository import Gtk as gtk

gi.require_version("Gdk", "3.0")  # apt install gir1.2-gtk-3.0
from gi.repository import Gdk as gdk

gi.require_version("WebKit2", "4.0")  # apt install gir1.2-webkit2-4.0
from gi.repository import WebKit2 as webkit2

from gi.repository import GLib as glib


APP_NAME = "Mini Browser"
APP_WM_CLASS = "mini-browser"
APP_ICON_NAME = "emblem-web"


def mini_browser(url, title=None, icon=None, wm_class=None):
 default_wm_class = APP_WM_CLASS
 
 if title is None:
  title = APP_NAME
 else:
  default_wm_class = title.strip() or default_wm_class
 
 if not wm_class:
  wm_class = default_wm_class
 
 if not icon:
  icon = APP_ICON_NAME
 
 url = list(urllib.parse.urlsplit(url))
 if not url[0]:
  url[0] = "http"
  url[1] = "/" + url[1]
 url = urllib.parse.urlunsplit(url)
 
 glib.set_prgname(wm_class)
 gdk.set_program_class(wm_class)
 
 w = gtk.Window()
 w.set_title(title)
 w.set_icon_name(icon)
 w.set_size_request(1, 1)
 w.resize(1024, 576)
 w.connect("delete-event", _close_callback)
 
 s = gtk.ScrolledWindow()
 wv = webkit2.WebView()
 s.add(wv)
 w.add(s)
 
 wv.load_uri(url)
 
 w.show_all()
 gtk.main()


def _close_callback(window, data):
 window.hide()
 gtk.main_quit()


def main(argv):
 url = input("Please enter a URL: ") if len(argv) < 2 or argv[1] == "." else argv[1]
 title = argv[2] or None if len(argv) > 2 else None
 icon = argv[3] or None if len(argv) > 3 else None
 wm_class = argv[4] or None if len(argv) > 4 else None
 
 mini_browser(url, title, icon, wm_class)


if __name__ == "__main__":
 try:
  sys.exit(main(sys.argv))
 except KeyboardInterrupt:
  pass
