#!/bin/sh
set -e

escape_arg() {
 printf "'"
 printf '%s' "$1" | sed -e "s/'/'\\\\''/g"
 printf "'"
}

cmd="exec mpv"
for arg; do
 if [ -e "$arg" ]; then
  cmd="$cmd $(escape_arg "$(realpath "$arg")")"
 else
  cmd="$cmd $(escape_arg "$arg")"
 fi
done

eval "$cmd"
