#!/bin/sh

# *squawk* #


# Define penguins

obverse() {
 PENGUIN_PLAIN='<")'
 PENGUIN_COLOR='[0;31;40;91;100m<[37m")[0m'
 PENGUIN_SCREEN='%{= KR}<%{-}%{= Kw}")%{-} '
 PENGUIN_SCREEN_STATUS='{= KR}<{-}{= Kw}"){-} '
 PENGUIN_TMUX='#[default]#[fg=brightred,bg=brightblack]<#[fg=white]")#[default]'
}


reverse() {
 PENGUIN_PLAIN='(">'
 PENGUIN_COLOR='[0;37;40;100m("[91m>[0m'
 PENGUIN_SCREEN='%{= Kw}("%{-}%{= KR}>%{-} '
 PENGUIN_SCREEN_STATUS='{= Kw}("{-}{= KR}>{-} '
 PENGUIN_TMUX='#[default]#[fg=white,bg=brightblack]("#[fg=brightred]>#[default]'
}


# Set defaults

obverse

if [ -t 1 ]; then
 PENGUIN="PENGUIN_COLOR"
else
 PENGUIN="PENGUIN_PLAIN"
fi


# Option handling

for i; do
 if [ "$i" = "-h" ] || [ "$i" = "--help" ]; then
  cat <<USAGE
Usage: $0 [OPTIONS]

Displays a simple ASCII art penguin head.

Options:

    -c, --color, --colour          Displays the penguin in colour using ANSI
                                   escape sequences.  This is the default if
                                   standard output is a terminal.
    
    -p, --plain,                   Displays the penguin without ANSI escape
    -n, --no-color, --no-colour    sequences.  This is the default if standard
                                   output is not a terminal.
    
    -s, --screen                   Displays the penguin using GNU screen escape
                                   sequences.
    
    -S, --screen-hardstatus        Displays the penguin using GNU screen escape
                                   sequences, using ^E as the escape sequences
                                   (for use inside of a window's hardstatus).
    
    -T, --tmux                     Displays the penguin using tmux escape
                                   sequences.
    
    -r, --reverse                  Displays the penguin in reverse (facing
                                   right instead of left).
    
    -h, --help                     Displays this help and exits.

USAGE
  exit 0
 fi
 
 if [ x"$i" = x"--hep" ]; then
  echo "Hep!  Hep!  I'm covered in sawlder! ... Eh?  Nobody comes."
  echo "--Red Green (episode 102), https://www.youtube.com/watch?v=qVeQWtVzkAQ#t=6m27s"
  exit 0
 fi
 
 if [ x"$i" = x"-r" ] || [ x"$i" = x"--reverse" ]; then
  reverse
 elif [ x"$i" = x"-s" ] || [ x"$i" = x"--screen" ]; then
  PENGUIN="PENGUIN_SCREEN"
 elif [ x"$i" = x"-S" ] || [ x"$i" = x"--screen-hardstatus" ] || \
      [ x"$i" = x"--screen-status" ]; then
  PENGUIN="PENGUIN_SCREEN_STATUS"
 elif [ x"$i" = x"-T" ] || [ x"$i" = x"--tmux" ]; then
  PENGUIN="PENGUIN_TMUX"
 elif [ x"$i" = x"-p" ] || [ x"$i" = x"--plain" ] || \
      [ x"$i" = x"-n" ] || [ x"$i" = x"--no-color" ] || \
      [ x"$i" = x"--no-colour" ]; then
  PENGUIN="PENGUIN_PLAIN"
 elif [ x"$i" = x"-c" ] || [ x"$i" = x"--color" ] || [ x"$i" = x"--colour" ]; then
  PENGUIN="PENGUIN_COLOR"
 fi
done


# Resolve and print

PENGUIN="$(eval "printf %s \"\$$PENGUIN\"")"
printf '%s\n' "$PENGUIN"
