#!/bin/sh

# Displays a placeholder window with the specified size.
# The window border is not included in the window's size.
# Omitting the height will result in a square window.

# Known issue:  xwininfo reports a geometry of (width-1)x(height-1),
#               even though the window is actually the correct size
#               (at least for me).

if [ -z "$1" ]; then
 echo "Usage: $0 [-q|-quiet|-s|-silent] <width>[x<height>]"
 exit 2
fi

QUIET=0
if (printf '%s' "$1" | egrep -qe "^(-q|--?quiet|-s|--?silent)$"); then
 QUIET=1
 shift
fi

SIZE="$1"
if (printf '%s' "$SIZE" | grep -q -v "x"); then
 SIZE="$1x$1"
fi

URL="http://placehold.it/$SIZE"
TITLE="$SIZE Placeholder"

shift
([ "$QUIET" -eq 1 ] && curl -s -L "$URL" || curl -L "$URL") \
 | display -title "$TITLE" "$@" -
