#!/bin/bash

if [ -n "$2" ]; then
 RE="\b$1/$2"
else
 RE="\b$1\b"
fi

if [ -e "/usr/share/nmap/nmap-services" ]; then
 grep -i "$RE" /usr/share/nmap/nmap-services
else
 grep -i "$RE" /etc/services
fi
