#!/bin/bash

function psgrep() {
 if [ -z "$1" ]; then
  echo "Usage: $0 pattern"
  return 1
 fi
 heading="`ps aux | head -n1`"
 echo -e '\x1b[1m'"$heading"'\x1b[0m'
 processes="`ps aux`"
 grep "$@" <<< "$processes" | egrep -v "^$USER\\s+$$\s"
}

psgrep "$@"
