#!/bin/sh

psgrep() {
 local hide_parent=0
 if [ x"$1" = x"-p" ] || [ x"$1" = x"--hide-parent" ]; then
  hide_parent=1
  shift
 elif [ x"$1" = x"--" ]; then
  shift
 fi
 if [ x"$1" = x"" ]; then
  echo "Usage: $0 [-p|--hide-parent|--] pattern"
  return 2
 fi
 
 local header="`ps aux | head -n1`"
 printf '\033[1m%s\033[0m\n' "$header"
 local processes="`ps aux`"
 if [ $hide_parent -ne 0 ]; then
  printf '%s' "$processes" | grep "$@" \
   | egrep -v "^$USER\\s+$$\\s" | egrep -v "^\\S+\\s+$PPID\\s"
 else
  printf '%s' "$processes" | grep "$@" \
   | egrep -v "^$USER\\s+$$\\s"
 fi
}


pswatch() {
 local interval=
 if (printf '%s' "$1" | grep -q -e '^[0-9]\+\(\.[0-9]\+\)\?$'); then
  interval="n$1"
  shift
 elif [ x"$1" = x"--" ]; then
  shift
 fi
 if [ x"$1" = x"" ]; then
  echo "Usage: pswatch [interval (s)|--] pattern"
  return 2
 fi
 export PSGREP="$0"
 exec watch -c"$interval" -x sh -c '. "$PSGREP"' 'psgrep' -p "$@"
}


if [ x"$(basename "$0" .sh)" = x"pswatch" ]; then
 pswatch "$@"
else
 psgrep "$@"
fi
