#!/bin/sh

psgrep() {
 local hide_parent=0
 if [ x"$1" = x"-p" ] || [ x"$1" = x"--hide-parent" ]; then
  hide_parent=1
  shift
 elif [ x"$1" = x"--" ]; then
  shift
 fi
 if [ x"$1" = x"" ]; then
  echo "Usage: $0 [-p|--hide-parent|--] pattern"
  return 2
 fi
 
 local ps=ps\ auwwx
 if ! $ps >/dev/null 2>&1; then
  ps=ps\ ww
 fi
 if ! $ps >/dev/null 2>&1; then
  ps=ps
 fi
 
 local header="`$ps | head -n1`"
 local out="`$ps`"
 local user_re='^\(\S\+\s\+\)\?\s*'
 if [ $hide_parent -ne 0 ]; then
  out=$(printf '%s' "$out" | grep "$@" | grep -v -e "$user_re$$\\s" \
   -e "$user_re$PPID\\s" -e "$user_re${__PSWATCH:-%}\\s")
 else
  out=$(printf '%s' "$out" | grep "$@" | grep -v "$user_re$$\\s")
 fi
 if [ $? -eq 0 ]; then
  printf '\033[1m%s\033[0m\n' "$header"
  printf '%s\n' "$out"
 else
  return 1
 fi
}


pswatch() {
 local ntrvl=
 if (printf '%s' "$1" | grep -q '^[0-9]\+\(\.[0-9]\+\)\?$'); then
  ntrvl="-n$1"
  shift
 elif [ x"$1" = x"--" ]; then
  shift
 fi
 if [ x"$1" = x"" ]; then
  echo "Usage: pswatch [interval (s)|--] pattern"
  return 2
 fi
 export __PSWATCH=$$
 if readlink -f "$(which watch)" | grep -q '/watch$'; then
  exec watch -c $ntrvl "$0" -p "$@"
 else
  exec watch $ntrvl "$0" -p "$@"
 fi
}


if [ x"$(basename -- "$0" .sh)" = x"pswatch" ] && [ x"$__PSWATCH" = x"" ]; then
 pswatch "$@"
else
 psgrep "$@"
fi
