#!/usr/bin/env python3

import os
import subprocess
import sys


def run_until_successful(cmd):
 r = None
 while r != 0:
  r = subprocess.call(cmd)

def main(argv):
 if len(argv) < 2:
  print("Usage: %s command [args [...]]" % os.path.basename(argv[0]), file=sys.stderr)
  return 2
 
 run_until_successful(argv[1:])


if __name__ == "__main__":
 try:
  sys.exit(main(sys.argv))
 except KeyboardInterrupt:
  pass
