#!/usr/bin/env python2

import os, subprocess, sys

args = sys.argv
if len(sys.argv) > 1:
	args = sys.argv[1:]
else:
	print "Usage: %s command" % os.path.basename(sys.argv[0])
	sys.exit(2)

command = args

def run_until_successful(cmd):
	returncode = 1
	while returncode is not 0:
		returncode = subprocess.call(cmd)

try:
	run_until_successful(command)
except:
	print 
