#!/bin/sh

KEYSTORE=/home/scottywz/.android/release.keystore
ALIAS=androidreleasekey

if [ "$1" = "--verbose" -o "$1" = "-v" ]; then
 VERBOSE=1
 shift
else
 VERBOSE=0
fi

SRC="$1"
APK="$2"
APK_U="$2".unaligned

if [ -z "$APK" ]; then
 if grep -q -e '-unsigned\.apk$' <<< "$SRC"; then
  APK=$(sed -e 's/-unsigned\.apk$/.apk/g' <<< "$SRC")
 fi
fi

if grep -q -e '\.apk$' <<< "$APK"; then
 APK_U=$(sed -e 's/\.apk$/-unaligned.apk/g' <<< "$APK")
fi

if [ -z "$APK" -o -z "$SRC" ]; then
 echo "Usage: $(basename "$0") [-v|--verbose] input-apk output-apk" >&2
 echo "If \`input-apk\` ends in \"-unsigned.apk\", then \`output-apk\` may be omitted" >&2
 echo "and \`input-apk\` with \"-unsigned.apk\" removed will be used." >&2
 exit 2
fi

cp -a "$SRC" "$APK_U"
[ $VERBOSE -ne 0 ] && echo jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \\
[ $VERBOSE -ne 0 ] && echo '          '-keystore "$KEYSTORE" "$APK_U" "$ALIAS"
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
          -keystore "$KEYSTORE" "$APK_U" "$ALIAS"

rm -f "$APK"
[ $VERBOSE -ne 0 ] && echo zipalign 4 "$APK_U" "$APK"
zipalign 4 "$APK_U" "$APK"
