#!/usr/bin/env python3

import os
import sys
import urllib.parse

try:
 import readline
except ImportError:
 pass


def main(argv):
 server_url = input("Enter server address and port number: ")
 server_url = urllib.parse.urlparse("//" + server_url)

 args = ["ssh"] + sys.argv[1:]
 if server_url.port and server_url.port != 22:
  args += ["-p", str(server_url.port)]
 if server_url.username:
  args += ["-l", server_url.username]
 args += [server_url.hostname]

 try:
  os.system("clear")
 except OSError:
  pass

 os.execvp("ssh", args)


if __name__ == "__main__":
 try:
  sys.exit(main(sys.argv))
 except (KeyboardInterrupt, EOFError):
  pass
