#!/usr/bin/env python2

import os
import sys
import urlparse

try:
 import readline
except ImportError:
 pass

def main(argv):
 server_url = raw_input("Enter server address and port number: ")
 server_url = urlparse.urlparse("//" + server_url)

 args = ["ssh"] + sys.argv[1:]
 if server_url.port and server_url.port != 22:
  args += ["-p", str(server_url.port)]
 if server_url.username:
  args += ["-l", server_url.username]
 args += [server_url.hostname]

 try:
  os.system("clear")
 except EnvironmentError:
  pass

 os.execvp("ssh", args)

if __name__ == "__main__":
 try:
  sys.exit(main(sys.argv))
 except (KeyboardInterrupt, EOFError):
  pass
