#!/bin/bash

# My (Scott Zeid) script to start Thunderbird

# Distribution version
THUNDERBIRD_CMD=/usr/bin/thunderbird

# Custom install
#THUNDERBIRD_CMD=/home/scottywz/opt/thunderbird/thunderbird

$THUNDERBIRD_CMD $@
