#!/bin/sh

# tmux-name
# Starts or resumes a tmux session with the given name and a minimal status bar.
# 
# Copyright (c) 2018-2021 S. Zeid.  Released under the X11 License.  
# <https://code.s.zeid.me/bin/blob/master/tmux-name>


STATUS_LEFT=$TMUX_NAME
STATUS_RIGHT='To detach, press Ctrl-Alt-C'
STATUS_POSITION=top
STATUS_BG=white
STATUS_FG=black


usage() {
 echo "Usage: $0 <session-name>[@host[:port]] [cmd [args [...]]]"
}


main() {
 if [ $# -lt 1 ]; then
  usage >&2
  exit 2
 fi
 
 local script=
 if printf '%s\n' "$1" | grep -q -e '/' && [ -x "$1" ]; then
  if [ x"$(head -n 1 "$1")" = x"#!/usr/bin/env $(basename -- "$0")" ]; then
   script=$1
  fi
 fi
 
 export TMUX_NAME="$(basename -- "$1")"
 shift
 
 if (printf '%s\n' "$TMUX_NAME" | grep -q -e '@'); then
  local hostname="${TMUX_NAME#*@}"
  local port=
  TMUX_NAME=${TMUX_NAME%%@*}
  if [ x"$TMUX_NAME" = x"" ] || [ x"$hostname" = x"" ]; then
   usage >&2
   exit 2
  fi
  if [ x"$hostname" != x"" ]; then
   if (printf '%s\n' "$hostname" | grep -q -e ':'); then
    port=${hostname##*:}
    hostname=${hostname%:*}
    if [ x"$port" = x"" ]; then
     usage >&2
     exit 2
    fi
   fi
   exec ssh -t \
    ${port:+-p} ${port:+$port} "$hostname" \
    "$(basename -- "$0")" "$TMUX_NAME" "$@"
  fi
 fi
 
 if [ x"$1" = x"__setup_tmux" ]; then
  setup_tmux
 elif (tmux -L "$TMUX_NAME" has-session -t "$TMUX_NAME" 2>/dev/null); then
  tmux -L "$TMUX_NAME" attach -t "$TMUX_NAME"
 else
  local cmd=
  if [ x"$script" != x"" ]; then
   set -- '/bin/sh' '-c' '. "$1"' "$TMUX_NAME" "$script"
  elif [ $# -eq 0 ]; then
   set -- "${SHELL:-/bin/sh}"  # default command
  fi
  for i; do
   cmd="$cmd '$(escape_arg "$i")'"  # escape arguments
  done
  
  tmux -L "$TMUX_NAME" new-session -s "$TMUX_NAME" -n "$TMUX_NAME" \
   "export TMUX_NAME='$(escape_arg "$TMUX_NAME")'; export TERM=screen-256color;
    '$(escape_arg "$0")' \"\$TMUX_NAME\" __setup_tmux;
    $cmd"
 fi
}


escape_arg() {
 printf '%s' "$1" | sed -e "s/'/'\\\\''/g"
}


setup_tmux() {
 tmux bind-key -n C-M-c detach-client
 tmux set-option -g default-terminal "$TERM"
 tmux set-option -g status-bg "$STATUS_BG"
 tmux set-option -g status-fg "$STATUS_FG"
 tmux set-option -g status-position "$STATUS_POSITION"
 tmux set-option -g status-left "$STATUS_LEFT "
 tmux set-option -g status-left-length 24
 tmux set-option -g status-right "$STATUS_RIGHT"
 tmux set-option -g status-right-length 37
 tmux set-window-option window-status-current-format 'on #H'
 tmux set-window-option window-status-format 'on #H (window #I)'
 tmux set-window-option window-status-separator ' '
}


main "$@"
